#TODO check if really needed because it was commented in symfony v3 config
doctrine_cache:
  providers:
    my_markdown_cache:
      type: '%cache_type%'
      file_system:
        directory: '%kernel.cache_dir%/markdown_cache'